
name: funny jokes

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  test: funny joke

    runs-on:ubuntu-latest

    steps:
    - uses: 
    - name: 
    monkey.html
      uses:
      with:
        ruby-version: 2.6
        https://www.npr.org/sections/goatsandsoda/2017/06/07/531586948/quiz-guess-what-this-monkey-face-means
    - name: 
      run: 
    - name: 
      run: 
- name: 
  uses: 
  with:
    
    always-auth: 
    
    node-version: 
    
    
    registry-url: 
    scope:.
    token:
    version: 
